version: 2
jobs:

  build:
    working_directory: ~/build
    docker:
      - image: microsoft/dotnet:2.0.4-sdk-2.1.3
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    steps:
      - run:
          name: Print environment versions
          command: |
            NPM_V=$(npm -v)
            echo npm version':' $NPM_V
            DOTNET_CLI_V=$(dotnet --version)
            echo dotnet cli version':' $DOTNET_CLI_V
      - checkout
      - run:
          name: dotnet restore
          command: dotnet restore ReactWindows
      - run:
          name: dotnet build 
          command: dotnet build ReactWindows
      - run:
          name: dotnet test
          command: dotnet test ReactWindows --logger \"trx;LogFileName=test-results.xml\"
      - run:
          name: Check Test
          command: if [[ -e test-results.xml ]]; then cp test-results.xml $CIRCLE_TEST_REPORTS/test-results.xml; fi
      - save_cache:
          key: reactnativewindows-{{ .Branch }}-{{ checksum "react-native-windows/ReactWindows/ReactNative/ReactNative.csproj" }}
          paths:
            - ~/.nuget

# uncomment when Microsoft github org adds CircleCI Mac support
#    macos:
#      xcode: "8.3.3"

#      - run:
#          name: Install dotnet (core) sdk
#          command: brew install caskroom/cask/dotnet-sdk

